version: '3'

services:

  app:
    build: .
    container_name: api-tech
    entrypoint: dockerize -template ./.docker/app/.env:backend/.env -wait tcp://db:3306
      -timeout 40s ./.docker/entrypoint.sh
    ports:
      - "8080:8080"
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=db_tech
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: .docker/nginx
    container_name: nginx-tech
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: db-tech
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_tech
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
